name: BUILD - run tests, then build and binary upload

# Run the unit-tests and ibctest jobs concurrently,
# and if both succeed, then run the build binary and upload step.

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout relayer
        uses: actions/checkout@v2

      - name: run unit tests
        run: make test

  ibctest:
    name: ibctest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: checkout relayer
        uses: actions/checkout@v2

      - name: run lightweight ibc tests
        run: make ibctest

  build:
    name: build
    runs-on: ubuntu-latest
    needs: ["unit-tests", ibctest]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: checkout relayer
        uses: actions/checkout@v2

      - name: build binary and move to upload location
        run: make build

      # upload resulting binaries
      - name: upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: rly
          path: ./build/rly